name: Auto Comment
on: 
  issues:
    types: [opened]

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write' #__This fixed the HttpError: Resource not accessible by integration


jobs:

  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with api
#         run: |
#           gh api -X POST \
#           https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments} \
#           -f body='
#             Comment but from the api call not action
#           '
        run: |
          # GitHub CLI api
          # https://cli.github.com/manual/gh_api

          gh api -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${OWNER}/${REPO}/issues/${ISSUE_NUMBER}/comments \
            -f body='
              Message from api call
            '
            
        shell: bash
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          OWNER: '${{ github.event.repository.owner.login }}'
          REPO: '${{ github.event.repository.name }}'
          ISSUE_NUMBER: '${{ github.event.issue.number }}'
