name: Crate comment on new issues

on:
  issues:                   # workflow will be triggered by issues
    types: [opened]         # more precise when one issue is oppened

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context    "
        run : echo '${{ toJSON(github.event) }}'
        shell: bash

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: '${{ github.event.issue.number }}'
          body: |
            This is a multiline automatically 
            generated comment
          reactions: '+1'
